# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [] }:
let
  version = "63d7a30";
  revision = "63d7a30503c803f1960ca6a1ba6a33c6f9463c1b";
in
(
  applyPatches {
    src = fetchFromGitHub {
      owner = "glitch-soc";
      repo = "mastodon";
      rev = "${revision}";
      hash = "sha256-BYBzWLG6tU53G3h/hV7HNP9sDrRPkIcsE2L2HD0cb0A=";
    };
    patches = patches ++ [./yarn-typescript.patch];
  }) // {
  inherit version;
  yarnHash = "sha256-CIIz5wwWzvDKc/VbSIT7Z5D9kwOLoErXoO0WQWfV/g4=";
}
